@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "inheritanceDemo.Client#main(String[])",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "inheritanceDemo.Client",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1265916365 { 
   	label=inheritanceDemo
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1660853269 { 
   	label=Cat
	labeljust=l
	fillcolor=white
	style=filled
   
   Cat1265916365XXXsound0[
	label="+ sound()"
	style=filled
	fillcolor=white
	tooltip="Cat

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1660854651 { 
   	label=Dog
	labeljust=l
	fillcolor=white
	style=filled
   
   Dog1265916365XXXsound0[
	label="+ sound()"
	style=filled
	fillcolor=white
	tooltip="Dog

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_411014493 { 
   	label=Animal
	labeljust=l
	fillcolor=white
	style=filled
   
   Animal1265916365XXXeat0[
	label="+ eat()"
	style=filled
	fillcolor=white
	tooltip="Animal

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_466418476 { 
   	label=Client
	labeljust=l
	fillcolor=white
	style=filled
   
   Client1265916365XXXmain1859653459[
	label="+ main()"
	style=filled
	fillcolor=white
	tooltip="Client

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_637658674 { 
   	label=Elephant
	labeljust=l
	fillcolor=white
	style=filled
   
   Elephant1265916365XXXsound0[
	label="+ sound()"
	style=filled
	fillcolor=white
	tooltip="Elephant

null"
	fontcolor=darkgreen
];
} 
} 

'edges    
Client1265916365XXXmain1859653459 -> Animal1265916365XXXeat0;
Client1265916365XXXmain1859653459 -> Cat1265916365XXXsound0;
Client1265916365XXXmain1859653459 -> Dog1265916365XXXsound0;
Client1265916365XXXmain1859653459 -> Elephant1265916365XXXsound0;
    
}
@enduml